version: "3.8"

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 1s
      retries: 10

  hermod-admin:
    image: pustovitdmytro/hermod-admin:1
    container_name: hermod-admin
    ports:
      - "9001:8010"
    env_file:
      - ./hermod.env
    depends_on:
      redis:
        condition: service_healthy

  hermod-worker:
    image: pustovitdmytro/hermod-worker:1
    container_name: hermod-worker
    env_file:
      - ./hermod.env
    depends_on:
      redis:
        condition: service_healthy

volumes:
  redis_data:
